### ISSUE TITLE
gafferCycles prevent gaffer to start

### ISSUE THREAD

**Issue by Kaiz3rTool** [boberfly/GafferCycles#18]
hi,
with gaffer 0.54.*, application wont start if gafferCycles is up. 
terminal return : 

`ERROR : startup/gui/menus.py : Error loading Cycles module - "/opt/gafferCycles/lib/libGafferCycles.so: undefined symbol: _ZTIN3ccl4NodeE".
 Traceback (most recent call last):
  File "/opt/gafferCycles/startup/gui/menus.py", line 61, in <module>
    import GafferCycles
  File "/opt/gafferCycles/python/GafferCycles/__init__.py", line 39, in <module>
    from _GafferCycles import *
ImportError: /opt/gafferCycles/lib/libGafferCycles.so: undefined symbol: _ZTIN3ccl4NodeE
`

centos 7.6
gaffer 0.54.1.0 & 0.54.0.1
gafferCycles 0.6.0 release

**Comment by boberfly** [comment]
Hi @Kaiz3rTool 
You are using a version that I haven't built against yet, did Gaffer 0.54.0.1 not work? In debug mode it was working here, perhaps the release build has a problem. I'll take a look into it and also build against 0.54.1.0.

**Comment by boberfly** [comment]
@Kaiz3rTool ok I can reproduce it here, oddly debug builds work fine but release builds cause this symbol issue. I will need a bit of time to get to the bottom of this as it doesn't look very obvious what is causing it.

**Comment by boberfly** [comment]
@Kaiz3rTool this was a tricky bug to spot, but it was in Cycles itself. I've made a diff for them to review here:
https://developer.blender.org/D5590
Please try this release:
https://github.com/boberfly/GafferCycles/releases/tag/0.6.1

Cheers

**Comment by Kaiz3rTool** [comment]
Hi, sorry I'm taking for ever to answer...
yes I have the bug with both 0.54.0.1 and 0.54.1.0
the release 0.6.1 of gaffercycles works well to me, thanks !
