### ISSUE TITLE
free(): corrupted unsorted chunks

### ISSUE THREAD

**Issue by edmondeng** [boberfly/GafferCycles#19]
Hey Alex,

I have a super simple scene which crashes when I click the render button.

Here is the stack trace:

700, child_tidptr=0x7f8a80c8b9d0) = 11219
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f89d13ce000
mprotect(0x7f89d13cf000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f89d1bcdfb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f89d1bce9d0, tls=0x7f89d1bce700, child_tidptr=0x7f89d1bce9d0) = 11220
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f89d0bcd000
mprotect(0x7f89d0bce000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f89d13ccfb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f89d13cd9d0, tls=0x7f89d13cd700, child_tidptr=0x7f89d13cd9d0) = 11221
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=4*1024}) = 0
openat(AT_FDCWD, "/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 31
read(31, "0-15\n", 8192)                = 5
close(31)                               = 0
futex(0x7f8aace70eac, FUTEX_WAKE, 1)    = 1
futex(0x7f8aace7102c, FUTEX_WAKE, 1)    = 1
sched_yield()                           = 0
futex(0x7f8aace7102c, FUTEX_WAKE, 1)    = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
futex(0x7f8aace70fac, FUTEX_WAKE, 1)    = 1
futex(0x7f8aace710ac, FUTEX_WAKE, 1)    = 1
pread64(30, "/\0\0\0\0\0\0\0", 8, 2121144) = 8
pread64(30, "\vE\212<w\342\10\354_*\203\3057\3318\224", 16, 2121167) = 16
pread64(30, " \0\0\0\0\0\0\0", 8, 2121038) = 8
pread64(30, "\301\260+\332\242?\354\224\177\f\21WO\263\372\211", 16, 2121046) = 16
free(): corrupted unsorted chunks
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)

**Comment by boberfly** [comment]
Hey Edmond,
Yeah that doesn't tell me much to help fix. Have you tried a MeshType node to re-calculate the normals on the mesh? That's the major bug that I know for now until I figure out a way to fix what's up.

**Comment by edmondeng** [comment]
Ok It’s a sphere node inside gaffer which I am rendering lemme check that .. is that a requirement for any mesh or was that mesh type for fixing certain cases? I’ll have a go later today

**Comment by boberfly** [comment]
You might need to give me a .gfr because it seems to work fine here, with the latest release from me.
![Screenshot_20190922_141947](https://user-images.githubusercontent.com/5601445/65394530-203e9e00-dd44-11e9-8632-68691d3cf636.png)

**Comment by boberfly** [comment]
Going to close this as things have changed/stabilised greatly since this build.
