### ISSUE TITLE
GPU rendering

### ISSUE THREAD

**Issue by Kaiz3rTool** [boberfly/GafferCycles#22]
hi, not sure if it's implented or not for now
from my side I only have CPU options, even with the experimental box turned on

best

**Comment by boberfly** [comment]
Hi @Kaiz3rTool 

Currently I am getting GPU rendering to work via OpenCL on a Vega Frontier Edition & CUDA on a Geforce RTX 2070 (OptiX is a little stubborn though on my RTX 2070 I'm not too sure why that's not working yet).

Are you not getting the devices appearing in CyclesOptions ? Check if Blender 2.80 lets you pick any, it could be out of date drivers or no Cuda installed, by the looks of it they don't pre-build the kernels on the later Cuda versions for some reason.

**Comment by Kaiz3rTool** [comment]
hi, i don't see any gpu device from gaffer

![image](https://user-images.githubusercontent.com/4272733/67067802-f2e4e480-f177-11e9-8f7a-52d57da12dcb.png)

 all is fine in blender where my 7 GPU are present : 

![image](https://user-images.githubusercontent.com/4272733/67067722-af8a7600-f177-11e9-8252-492f334e78cd.png)

maybe the problem come from that I was refering in the OSL issue thread, the Nvidia nvcc error I have on starting gaffercycles 

which: no nvcc in (/opt/gaffer-0.54.2.0-linux/appleseed/bin:/opt/gaffer-0.54.2.0-linux/bin:/opt/gaffer-0.54.2.0-linux/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/william/.local/bin:/home/william/bin:/opt/Arnold/bin:/opt/3delight-1.4.1/bin:/mnt/Pipeline/Gaffer/deadline/bin:/opt/gafferCycles/bin)

**Comment by boberfly** [comment]
Whoa that's a lot of GPUs! It could be the fact that multiple ones of the same kind is tripping up my code here. I don't have such a configuration but perhaps I can go by this and track it down, or find a computer with more than two GPUs of the same kind...

**Comment by Kaiz3rTool** [comment]
haha yes, I have a bunch of them, I should have 8 one but one died last day so it's not visible here
i can do some tests if needed for multigpu supports

the nvcc error was only with gaffercycles, nothing happened with other softwares or blender when using cycles cpu and gpu.
I tried to install cuda, it seems to fix the problem as I dont have nvcc error and gpu is available in gaffer (I can see a single one),

![image](https://user-images.githubusercontent.com/4272733/67088886-90efa380-f1a6-11e9-9dbb-0f086e2a09bc.png)

for now it doesn't render as I have cuda 7.5 and it need 8.0 minimum
I will let you know 

cheers
thanks !

**Comment by boberfly** [comment]
That's a better sign now. I made a late 0.10.1 build last night which builds up to sm7.5 hardware which I believe is RTX hardware, the line was missing from Cycles standalone but present in regular Blender which I think removes the need for nvcc at runtime. I was able to successfully run OptiX now after doing that but that requires Nvidia's 435.21 driver as a minimum.

**Comment by Kaiz3rTool** [comment]
hi again, 
the last update works well to me with driver 430.50 (as I run it on server I use only Long Lived Branch drivers) I can now render on GPU 

In the multi device part i can now see all my GPUs
![image](https://user-images.githubusercontent.com/4272733/67116364-8ce07780-f1e0-11e9-9240-0f0340765783.png)

About the optix part, I didn't found where to activate it

**Comment by boberfly** [comment]
Excellent! Although bare in mind I want to change this UI eventually so that it uses the +/- icons to add/remove devices as a list that can be interpreted as a varying sized list, that way if you launch a job on another machine it doesn't error if those devices are different but I need to figure out how to make that.

To get OptiX running you will need 435.21 minimum, apparently the logic for v7.0.0 onwards lives inside the driver, I believe it was a requirement for Blender to accept that and be compatible still with their license or something.

If you'd like we can discuss some things via email, I have a few things in-mind that I plan to do like incorporate some of the patches that don't exist in Blender 2.81 which I'd like to test out, especially on 7 2080ti's... ;)

**Comment by Kaiz3rTool** [comment]
ok, I will wait a little to have long term driver with optix then, or maybe on a more basic system

ahah, sure ! you can write me at william-at-dothefilm.fr
