### ISSUE TITLE
Gaffer>Settings>Variables image:catalog:port existence makes no render occur

### ISSUE THREAD

**Issue by edmondeng** [boberfly/GafferCycles#29]
So I am un-able to explain how this got into the global variables but on scenes which were rendering fine there was no entry and so on a scene which worked fine but recently stopped working I was able to delete this entry and things were going again.

Do we know when these variables appear and why?
![screenshot](https://user-images.githubusercontent.com/4751948/67922053-cf05a380-fb66-11e9-8365-d4f1b528914d.jpg)

**Comment by edmondeng** [comment]
The issue and solution Seems obvious yet the only real question is what scenario this is automatically put into the settings. I was running multiple sessions and was stopping starting renders in each session.

**Comment by boberfly** [comment]
Seems like a funky Gaffer-specific issue, going to close it.
