### ISSUE TITLE
lights in 0.12.0

### ISSUE THREAD

**Issue by acorsei** [boberfly/GafferCycles#35]
Hi @boberfly,
Seems like none of the lights are working in GafferCycles 0.12.0-experimental.
Please check enclosed simple script in case is something wrong on my end .
Thanks

[cycles_test.gfr.zip](https://github.com/boberfly/GafferCycles/files/3974972/cycles_test.gfr.zip)

**Comment by boberfly** [comment]
Hey @acorsei 

Try this:
[cycles_test.gfr.zip](https://github.com/boberfly/GafferCycles/files/3976353/cycles_test.gfr.zip)

It just needed a path filter to the sphere itself for the shader assignment. Assigning it to everything inadvertently looks like it applied the shader to the light also which just makes everything black.

Cheers

**Comment by acorsei** [comment]
all good! thanks
