### ISSUE TITLE
Hair rendering crashes

### ISSUE THREAD

**Issue by kubo-von** [boberfly/GafferCycles#38]
I don't know if this should be working or not yet.
But I've made a simple example scene with hair exported from Houdini. It works with Arnold but crashes with cycles:
`./gaffer.sh: line 8: 51608 Segmentation fault      (core dumped) ./gaffer`
I've uploaded the gaffer scenes and source alembic here:
[https://drive.google.com/drive/folders/1vJNTeAAqrYOB_4GQY032V1JsuPX4-D5J?usp=sharing](url)
Hope it helps!

**Comment by boberfly** [comment]
Hi @kubo-von 

Thank you for the test data I am after that kind of stuff to finish GafferCycles to 1.0, I'll throw this at the debugger and see what is happening soon.

Cheers

**Comment by boberfly** [comment]
Hey @kubo-von 
When I put a DeletePrimitiveVariables and removed customWidth (and left width alone) it seems to work and not crash. I am investigating now on why it is crashing though, but I can see where it is crashing (Cycles isn't giving me a data pointer to the attribute for some reason). I'll review this code soon which looks related to https://github.com/boberfly/GafferCycles/issues/40.

**Comment by kubo-von** [comment]
Hey @boberfly 
Yeah that seems to fix the crash. Thanks!

Another thing related to this is hair info node
[https://docs.blender.org/manual/en/latest/render/shader_nodes/input/hair_info.html](url)
Should it work or it's more of a Blender hair/particle system thing? 

Also in blender there are some settings for the curve subdivision [https://docs.blender.org/manual/en/latest/physics/particles/emitter/render.html#path](url)
and for the hair width. 
[https://docs.blender.org/manual/en/latest/physics/particles/hair/shape.html](url)
(although I think that controlling thickness it with width vertex attribute makes more sense)
Maybe these would be good to have in the CyclesAttributes node ? 

Cheers

**Comment by boberfly** [comment]
Hey @kubo-von 

Those values are in the CyclesOptions, as they're currently globals to Cycles and not per-object for some reason.

Cheers

**Comment by boberfly** [comment]
About the hair_info shader, the code converting curves & particles is very confusing in the Blender-side when it refers to particles, I haven't looked into the specifics of this yet but perhaps it just requires specifically named primvars to function, the notion of "particles" is Blender-centric from what I remember when digging into it when it really means per-strand primvar.
