### ISSUE TITLE
GPU not showing in devices

### ISSUE THREAD

**Issue by kubo-von** [boberfly/GafferCycles#39]
My GPU is not showing in devices. It works fine with cycles in Blender both as optiX and CUDA device. Also GPU rendering with Arnold in gaffer works.
Is this expected to work ? Are there any tricks to make it show up ?
Thanks! 

Fedora 31
RTX 2070, driver 440.44

**Comment by boberfly** [comment]
Hi @kubo-von 

This is something which is happening for some people as well as the Windows build and I am not sure why, as it works great locally here in Linux with my RTX 2070. I have Cuda 10.2 installed so it might be why, but I am not sure what Blender is doing differently to make it work without the Cuda requirement (the cubin + optix ptx files are bundled with GafferCycles).

Cheers

**Comment by kubo-von** [comment]
After installing CUDA 10.2 rpm from here: https://developer.nvidia.com/cuda-downloads
GPU shows up and works, both as CUDA and OPTIX device.
Thanks a lot @boberfly !

**Comment by boberfly** [comment]
No worries @kubo-von but I would like to eventually get it to work without cuda so I will keep this open. Cheers!

**Comment by boberfly** [comment]
@kubo-von this build shouldn't need Cuda installed anymore:
https://github.com/boberfly/GafferCycles/releases/tag/0.16.0

**Comment by kubo-von** [comment]
Hey @boberfly, I can confirm 0.16.0 has GPU working even after removing Cuda. Thanks!

**Comment by boberfly** [comment]
Hey @kubo-von 

At least on Windows I am getting an error not finding the device in the console so it shows but it might not be working, I found a bug in Cycles itself where querying the devices twice gives different results. I am not sure if the devs will accept my patch so I have another idea to only do this query once. I'll keep this open until I do that.

**Comment by boberfly** [comment]
I think by https://github.com/boberfly/GafferCycles/commit/2bf952ad299c61f3cfcae2d32cc6ae95f60bac44 this should be resolved now and not fail to find the .cubin or .ptx files, nor fail on iterating available devices multiple times due to the IECoreCycles code caching all devices once at startup. Closing this one.

**Comment by Kaiz3rTool** [comment]
I revive it as I cant select my GPU without cuda, seems that it's works for you because something from cuda is still online
