### ISSUE TITLE
GafferCycles 0.20.0 crashing

### ISSUE THREAD

**Issue by pavelsiska** [boberfly/GafferCycles#49]
Hi Alex,
When I create any cycles node (in the latest build of Gaffer 0.57 and GafferCycles 0.20) that requires rendered preview Gaffer crashes immediately on my workstation (Ubuntu 19.10)
Leaving only "Segmentation fault (core dumped)" in the terminal.
Could it be something on my end?

**Comment by kubo-von** [comment]
The same is happening for me too. Creating any shader even in empty scene crashes when it tries to render it in the viewer. 
Fedora 31 here

**Comment by boberfly** [comment]
Hmm funky, this was stable for me here but you're not the only ones to report that. Possibly something changed in the Cycles codebase that I need to change, I'll take a look tonight.

**Comment by boberfly** [comment]
I'm on Ubuntu 18.04 here, but I am building and releasing in a docker container against CentOS7. I open a new scene against this build in Gaffer 0.57.0.0 and create a principled_bsdf, no crash.

Is regular Gaffer 0.57.0.0 working without crashes? Might be caused by something else...? What GPU/driver are you using? I pulled the RTX 2070 out of this machine so I am using a Vega FE with a bleeding edge open source Mesa driver.

**Comment by pavelsiska** [comment]
Thanks for looking into it.
Regular Gaffer 0.57 gives me shader previews in both Appleseed and Arnold with no crash.
I'm using GeForce GTX TITAN X, Nvidia-driver-435.

**Comment by kubo-von** [comment]
Same here, Appleseed works any cycles render crashes.
RTX 2070, 440.82

**Comment by boberfly** [comment]
So it crashed instantly on my laptop but my workstation was fine with it, very weird. Anyways making a build now.

**Comment by boberfly** [comment]
Please try this release and verify:
https://github.com/boberfly/GafferCycles/releases/tag/0.20.1

**Comment by pavelsiska** [comment]
Thanks, Alex. I can confirm the problem has been resolved. On my workstation, the latest release 0.20.1 runs without any problem.

**Comment by kubo-von** [comment]
0.20.1 works for me me too. Thanks a lot for the lightning-quick fix!

**Comment by boberfly** [comment]
Cheers, yeah a weird one for sure I'm always a bit worried with bugs like this which differ on the dev platform...
