### ISSUE TITLE
Disconnecting VDB from Group while rendering seg faults

### ISSUE THREAD

**Issue by redhoot-dev** [boberfly/GafferCycles#51]
GC 0.20 and GF 0.57.1 Happened every time I tried.

**Comment by boberfly** [comment]
Hey @redhoot-dev I haven't looked into this yet but some of the PR's from the 2.83 branch were related to VDB crashes for Blender itself. Not sure if they're the same, but I can look at this soon. Cheers.

**Comment by boberfly** [comment]
I am finding that it isn't crashing but in some scenes the removal of objects sometimes is delayed and won't sync quite right in-time, WDAS cloud seems to not be crashing for me at least. Also anything with emission or mesh lights adding/removing does crash it. Let me know if VDBs are crashing for you or if it's emissive objects rather.

**Comment by boberfly** [comment]
I think this could've been a bug with Cycles itself as this build was before their final stable release. Feel free to re-open.
