### ISSUE TITLE
Batch render with branched pathtracing rendering empty images 

### ISSUE THREAD

**Issue by kubo-von** [boberfly/GafferCycles#53]
Hey @boberfly !
Branched pathtracing seems to be crashing the render somehow, resulting image is empty. IPR runs fine, Switching to normal pathtracing fixes the problem, but since brached is the default this might be an issue that a lot of people run into. test scene: 
[cube.zip](https://github.com/boberfly/GafferCycles/files/4684755/cube.zip)

Cheers!

**Comment by boberfly** [comment]
Hey @kubo-von 

Yeah it's known, it's due to no default anti-alias value out of the box. Currently heavy in production atm so no eta on the fix.

**Comment by kubo-von** [comment]
Haha, that was fast!  Thanks @boberfly ! Closing

**Comment by boberfly** [comment]
Yeah had a boring evening, was raining... :)
