### ISSUE TITLE
libIex-2_3.so.24 not found

### ISSUE THREAD

**Issue by mrpurest** [boberfly/GafferCycles#57]
I am trying to run gaffer cycles with the latest version of gaffer and I am getting:

ERROR : startup/gui/menus.py : Error loading Cycles module - "libIex-2_3.so.24: cannot open shared object file: No such file or directory".

I understand this is part of "ilmbase", and I have an old version it seems.  -or is this due to me running a newer gaffer version?

**Comment by boberfly** [comment]
Hi @mrpurest 

Currently the builds are against the version listed in the package eg. 
[gafferCycles-0.22.1-gaffer-0.58.2.0-linux.tar.gz](https://github.com/boberfly/GafferCycles/releases/download/0.22.1/gafferCycles-0.22.1-gaffer-0.58.2.0-linux.tar.gz)
Would target Gaffer 0.58.2.0-linux and it may work in versions above eg. 0.58.**3**.0 but not on major versions eg. 0.**59**.6.0

New builds are overdue but I haven't had the time to make them. You can try @kubo-von 's builds here:
https://github.com/kubo-von/GafferCycles/releases

**Comment by mrpurest** [comment]
Success!  thanks for the links
